`timescale 1ns/1ps

module decoder_tb;

reg [1:0] A;
wire [3:0] Y;

decoder uut(
    .A(A),
    .Y(Y)
);

initial begin
    $dumpfile("decoder.vcd");
    $dumpvars(0, decoder_tb);

    A = 2'b00;
    #10;

    A = 2'b01;
    #10;

    A = 2'b10;
    #10;

    A = 2'b11;
    #10;

    $finish;
end

initial begin
    $monitor("Time=%0t A=%b Y=%b", $time, A, Y);
end

endmodule